version: '3.7'
services:
  enefti-backend:
    container_name: enefti-backend
    build:
      context: .
      dockerfile: release/Dockerfile
      labels:
        com.enefti.title: '@enefti/backend'
        com.enefti.description: 'NFT E-Commerce backend demo'
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '${PORT}:${PORT}'
    environment:
      - NODE_ENV=production
      - BASE_URL=${BASE_URL}
      - PORT=${PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    labels:
      com.enefti.title: '@enefti/backend'
      com.enefti.description: 'NFT E-Commerce backend demo'
    env_file:
      - .env
