#!/bin/bash

ALERTS=$(cat <<EOF
$1
EOF
)

for ALERT in $(echo $ALERTS | jq -r '.[] | @base64'); do
  ALERT_ID=$(echo $ALERT | base64 -d | jq -r '.id')

  echo "Processing alert $ALERT_ID"

  # Generate fix via Autofix API (POST /code-scanning/alerts/{alert_id}/autofixes)
  FIX_RESPONSE=$(gh api -X POST /repos/$2/code-scanning/alerts/$ALERT_ID/autofixes)
  FIX_ID=$(echo $FIX_RESPONSE | jq -r '.id')

  if [ "$FIX_ID" = "null" ]; then
    echo "No fix generated for $ALERT_ID"

    continue
  fi

  # Commit fix to dedicated branch
  BRANCH_NAME="autofix-codeql-$ALERT_ID"

  gh api -X POST /repos/$2/git/refs -f ref="refs/heads/$BRANCH_NAME" -F sha="$(git rev-parse HEAD)"

  # Apply fix
  COMMIT_RESPONSE=$(gh api -X POST /repos/$2/code-scanning/alerts/$ALERT_ID/autofixes/$FIX_ID/commit -F branch="$BRANCH_NAME" -F commit_message="fix: CodeQL alert $ALERT_ID")

  echo "Committed fix to $BRANCH_NAME"

  # Create draft PR
  PR_TITLE="Auto-fix: CodeQL alert #$ALERT_ID"
  PR_BODY="Generated by Copilot Autofix. Review and test before merge."
  PR_RESPONSE=$(gh pr create --title "$PR_TITLE" --body "$PR_BODY" --head "$BRANCH_NAME" --base "main" --draft)
  PR_NUMBER=$(echo $PR_RESPONSE | jq -r '.number')

  # Step 4: Assign to owner
  gh pr edit $PR_NUMBER --add-assignee $3
  # Close fixed alert
  gh api -X PATCH /repos/$2/code-scanning/alerts/$ALERT_ID -f state="fixed"
done
