name: eNefti CD
run-name: eNefti Content-Delivery
on:
  # Pipeline dependency
  workflow_run:
    workflows: [eNefti CI]
    types: [completed]
    branches: [main]
env:
  # GitHub Packages
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    # Pipeline Check
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      PORT: ${{ vars.PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./backend
          file: ./backend/release/Dockerfile
          build-args: |
            "BASE_URL=$BASE_URL"
            "PORT=$PORT"
            "DB_NAME=$DB_NAME"
            "DB_USER=$DB_USER"
            "DB_PASSWORD=$DB_PASSWORD"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=lc-2025/enefti:main
          cache-to: type=inline
      # Created files attestation storing as proof
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-push-image
    steps:
      - name: Deploy Backend
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
  # TODO: Add Frontend deployment
  failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
