name: eNefti CI
run-name: eNefti Content-Integration
on:
  push:
    branches: [main]
  # For collaborations
  pull_request:
    branches: [main]
jobs:
  setup-build-test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      PORT: ${{ vars.PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    - name: Allow MongoDB Atlas IP
      uses: textbook/atlas-ip@v1.1.0
      with:
        atlas-private-key: ${{ secrets.ATLAS_PRIVATE_KEY }}
        atlas-public-key: ${{ secrets.ATLAS_PUBLIC_KEY }}
        group-id: ${{ vars.ATLAS_GROUP_ID }}
    - name: Create `env` file and provide environment variables
      run: |
        touch .env
        echo BASE_URL=$BASE_URL >> .env
        echo PORT=$PORT >> .env
        echo DB_NAME=$DB_NAME >> .env
        echo DB_USER=$DB_USER >> .env
        echo DB_PASSWORD=$DB_PASSWORD >> .env
    - name: Installing dependencies, building packages and test applications
      run: |
        npm run setup
        npm run build
        # TODO: Include frontend too
        npm run test:ci -w @enefti/backend
    # Created files storing for future reuse
    - name: Archive production artifacts - Backend
      uses: actions/upload-artifact@v4
      with:
        name: production-backend
        path: backend/dist
    # Tests report storing for QA/checks
    - name: Archive code coverage results - Backend
      uses: actions/upload-artifact@v4
      with:
        name: cc-backend
        path: backend/coverage/**/*
