name: eNeFTi CI
run-name: eNeFTi Continuous-Integration
on:
  push:
    branches: [main]
  # For collaborations
  pull_request:
    branches: [main]
env:
  # Repository
  DEPENDENCIES_PATH: |
    ~/.cache
    ./node_modules
  DEPENDENCIES_KEY: '**/package-lock.json'
  ARTIFACTS_NAME: enefti
jobs:
  # Following jobs might be simplified into single one
  # Splitting as pipeline demonstration
  setup:
    runs-on: ubuntu-latest
    env:
      # Frontend
      FRONTEND_URL: ${{ vars.BASE_URL_FRONTEND }}
      NEXT_PUBLIC_BACKEND_URL: ${{ vars.BASE_URL_BACKEND }}
      # Backend
      BASE_URL: ${{ vars.BASE_URL_BACKEND }}
      PORT: ${{ vars.PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - name: Create `env` files and provide environment variables
        run: |
          touch .env
          echo FRONTEND_URL=$FRONTEND_URL >> .env
          echo NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL >> .env
          mv .env frontend/
          touch .env
          echo BASE_URL=$BASE_URL >> .env
          echo PORT=$PORT >> .env
          echo DB_NAME=$DB_NAME >> .env
          echo DB_USER=$DB_USER >> .env
          echo DB_PASSWORD=$DB_PASSWORD >> .env
          mv .env backend/
      - name: Installing dependencies
        run: npm run setup:ci
      # Cache dependencies for future reuse
      - name: Cache dependencies
        uses: actions/cache/save@v4
        with:
          path: ${{ env.DEPENDENCIES_PATH }}
          # Generate a new cache whenever packages or source files change.
          key: modules-${{ hashFiles(env.DEPENDENCIES_KEY) }}
      # Store project for future reuse
      - name: Archive project artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACTS_NAME }}
          # i.e. dotfiles
          include-hidden-files: true
          # Exclude dependencies to lighten artifacts (provided via cache)
          path: |
            .
            !./node_modules
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      # Get dependencies
      - name: Getting dependencies
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.DEPENDENCIES_PATH }}
          key: modules-${{ hashFiles(env.DEPENDENCIES_KEY) }}
          fail-on-cache-miss: true
      # Download stored project
      - name: Getting project artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACTS_NAME }}
      - name: Allow MongoDB Atlas IP
        uses: textbook/atlas-ip@v1.1.0
        with:
          atlas-private-key: ${{ secrets.ATLAS_PRIVATE_KEY }}
          atlas-public-key: ${{ secrets.ATLAS_PUBLIC_KEY }}
          group-id: ${{ secrets.ATLAS_GROUP_ID }}
      - name: Test applications
        run: npm run test
      - name: Test applications - E2E
        uses: cypress-io/github-action@v6
        with:
          working-directory: .
          project: ./frontend
          build: npm run build
          start: npm run start -w frontend
      # Tests report storing for QA/checks
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: enefti-test
          path: ./**/coverage/**/*
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Getting dependencies
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.DEPENDENCIES_PATH }}
          key: modules-${{ hashFiles(env.DEPENDENCIES_KEY) }}
          fail-on-cache-miss: true
      - name: Getting project artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACTS_NAME }}
      - name: Build packages
        run: npm run build
      - name: Cache production dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Archive production verions
        uses: actions/upload-artifact@v4
        with:
          name: enefti-production
          path: |
            ./backend
            ./frontend
            ./package*
